const test = require('node:test');
const assert = require('node:assert/strict');
const fs = require('node:fs');
const vm = require('node:vm');

const transcriptSource = fs.readFileSync(
  '/home/runner/work/yt-ai-summarizer/yt-ai-summarizer/content/transcript.js',
  'utf8'
);

function createHarness(options = {}) {
  const listeners = new Map();
  const state = {
    videoId: options.videoId || 'video12345678',
    trackResponses: [...(options.trackResponses || [])],
    transcriptResponses: [...(options.transcriptResponses || [])],
    transcriptDelayGate: options.transcriptDelayGate || null,
    quickTracks: options.quickTracks || (options.trackResponses?.[0] || []),
    trackRequestCount: 0,
    playerReadyAfterChecks: options.playerReadyAfterChecks || 0,
    playerReadyChecks: 0
  };

  class CustomEvent {
    constructor(type, init = {}) {
      this.type = type;
      this.detail = init.detail;
    }
  }

  const windowObj = {
    location: { href: `https://www.youtube.com/watch?v=${state.videoId}`, pathname: '/watch' },
    addEventListener(type, fn) {
      if (!listeners.has(type)) listeners.set(type, new Set());
      listeners.get(type).add(fn);
    },
    removeEventListener(type, fn) {
      listeners.get(type)?.delete(fn);
    },
    dispatchEvent(event) {
      if (event.type === 'ytai-request-player-prefs') {
        const detail = JSON.stringify({
          videoId: state.videoId,
          activeCaptionTrack: null,
          activeAudioTrackIndex: null,
          captionRouting: null
        });
        this.dispatchEvent(new CustomEvent('ytai-player-prefs-response', { detail }));
      }
      if (event.type === 'ytai-request-player-data') {
        const detail = JSON.stringify({ videoId: state.videoId, tracks: [] });
        this.dispatchEvent(new CustomEvent('ytai-player-data-response', { detail }));
      }
      const handlers = listeners.get(event.type);
      if (!handlers) return true;
      for (const handler of [...handlers]) handler(event);
      return true;
    }
  };

  const context = {
    window: windowObj,
    globalThis: null,
    navigator: { language: 'en-US' },
    URL,
    CustomEvent,
    DOMParser: class {
      parseFromString() {
        return { querySelectorAll: () => [] };
      }
    },
    document: {
      querySelector(selector) {
        if (selector !== '#movie_player') return null;
        state.playerReadyChecks += 1;
        if (state.playerReadyChecks <= state.playerReadyAfterChecks) return null;
        return {
          getVideoData: () => ({ video_id: state.videoId }),
          getPlayerResponse: () => ({
            videoDetails: { videoId: state.videoId },
            captions: {
              playerCaptionsTracklistRenderer: {
                captionTracks: state.quickTracks.map((t) => ({
                  baseUrl: t.baseUrl,
                  languageCode: t.language,
                  name: { simpleText: t.name || t.language },
                  kind: t.isAutoGenerated ? 'asr' : undefined,
                  vssId: t.vssId || t.language
                }))
              }
            }
          }),
          getOption: () => null
        };
      },
      querySelectorAll: () => []
    },
    StorageHelper: {
      outputLanguageToCaptionCode: (lang) => (lang === 'tr' ? 'tr' : null),
      getCachedTranscript: async () => null,
      cacheTranscript: async () => {}
    },
    chrome: {
      runtime: {
        sendMessage: async ({ action }) => {
          if (action === 'fetchCaptionTracks') return { tracks: [] };
          if (action === 'fetchTranscript') return { entries: [] };
          return {};
        }
      }
    },
    fetch: async (url) => {
      const raw = String(url);

      if (raw.startsWith('/youtubei/v1/player')) {
        const next = state.trackResponses.length
          ? state.trackResponses.shift()
          : [];
        state.trackRequestCount += 1;
        return {
          ok: true,
          json: async () => ({
            captions: {
              playerCaptionsTracklistRenderer: {
                captionTracks: (next || []).map((t) => ({
                  baseUrl: t.baseUrl,
                  languageCode: t.language,
                  name: { simpleText: t.name || t.language },
                  kind: t.isAutoGenerated ? 'asr' : undefined,
                  vssId: t.vssId || t.language
                }))
              }
            }
          })
        };
      }

      if (raw.includes('fmt=json3')) {
        if (state.transcriptDelayGate) await state.transcriptDelayGate;
        const next = state.transcriptResponses.length
          ? state.transcriptResponses.shift()
          : 'empty';
        const events = next === 'empty'
          ? []
          : [{ tStartMs: 0, segs: [{ utf8: next }] }];
        return { ok: true, text: async () => JSON.stringify({ events }) };
      }

      return { ok: false, text: async () => '' };
    },
    setTimeout,
    clearTimeout,
    console
  };

  context.globalThis = context;
  context.__YTAI_TRANSCRIPT_RUNTIME_CONFIG = {
    maxAttempts: 3,
    retryDelaysMs: [0, 0, 0],
    readinessTimeoutMs: 250,
    readinessPollMs: 5
  };

  vm.createContext(context);
  vm.runInContext(transcriptSource, context, { filename: 'transcript.js' });

  function setVideoId(videoId) {
    state.videoId = videoId;
    windowObj.location.href = `https://www.youtube.com/watch?v=${videoId}`;
  }

  return { tx: context.globalThis.TranscriptExtractor, state, setVideoId };
}

test('empty first attempt succeeds on second attempt', async () => {
  const h = createHarness({
    trackResponses: [
      [{ baseUrl: 'https://x/timedtext?lang=en', language: 'en' }],
      [{ baseUrl: 'https://x/timedtext?lang=en', language: 'en' }],
      [{ baseUrl: 'https://x/timedtext?lang=en', language: 'en' }]
    ],
    transcriptResponses: ['empty', 'hello world']
  });

  const result = await h.tx.getTranscript();
  assert.equal(result.fullText, 'hello world');
});

test('all attempts empty returns TRANSCRIPT_EMPTY_FINAL', async () => {
  const h = createHarness({
    trackResponses: [
      [{ baseUrl: 'https://x/timedtext?lang=en', language: 'en' }],
      [{ baseUrl: 'https://x/timedtext?lang=en', language: 'en' }],
      [{ baseUrl: 'https://x/timedtext?lang=en', language: 'en' }],
      [{ baseUrl: 'https://x/timedtext?lang=en', language: 'en' }]
    ],
    transcriptResponses: ['empty', 'empty', 'empty']
  });

  await assert.rejects(() => h.tx.getTranscript(), /TRANSCRIPT_EMPTY_FINAL/);
});

test('track list changes between attempts and selection is re-run', async () => {
  const h = createHarness({
    trackResponses: [
      [{ baseUrl: 'https://x/timedtext?lang=en', language: 'en', name: 'English' }],
      [{ baseUrl: 'https://x/timedtext?lang=tr', language: 'tr', name: 'Turkish' }]
    ],
    transcriptResponses: ['empty', 'merhaba dunya']
  });

  const result = await h.tx.getTranscript('tr');
  assert.equal(result.language, 'tr');
  assert.equal(result.fullText, 'merhaba dunya');
});

test('video id change isolates stale in-flight request', async () => {
  let release;
  const gate = new Promise((resolve) => { release = resolve; });
  const h = createHarness({
    trackResponses: [[{ baseUrl: 'https://x/timedtext?lang=en', language: 'en' }]],
    transcriptResponses: ['hello world'],
    transcriptDelayGate: gate
  });

  const pending = h.tx.getTranscript();
  h.setVideoId('video87654321');
  release();

  await assert.rejects(() => pending, /TRANSCRIPT_REQUEST_STALE/);
});

test('readiness waits until captions become available', async () => {
  const h = createHarness({
    playerReadyAfterChecks: 2,
    trackResponses: [
      [{ baseUrl: 'https://x/timedtext?lang=en', language: 'en' }],
      [{ baseUrl: 'https://x/timedtext?lang=en', language: 'en' }]
    ],
    transcriptResponses: ['ready now']
  });

  const result = await h.tx.getTranscript();
  assert.equal(result.fullText, 'ready now');
  assert.ok(h.state.playerReadyChecks >= 3);
});
