/**
 * Regression tests for caption-source fallthrough.
 *
 * Background: YouTube serves caption URLs that return HTTP 200 with an empty
 * body. A track source can therefore hand back a full track list whose every
 * URL is dead. The extractor must keep walking its remaining sources instead
 * of treating the first source that produced tracks as the final word.
 */
const test = require('node:test');
const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');
const vm = require('node:vm');

const transcriptSource = fs.readFileSync(
  path.join(__dirname, 'transcript.js'),
  'utf8'
);

const DEAD = 'https://x/timedtext?lang=en&dead=1';
const LIVE = 'https://x/timedtext?lang=en&live=1';

/**
 * @param options.clientTracks  map of innertube clientName -> track list
 * @param options.liveUrls      caption URLs that return real content
 * @param options.bridgeTracks  tracks returned by the MAIN-world page bridge
 * @param options.proxyTracks   tracks returned by the service-worker proxy
 */
function createHarness(options = {}) {
  const listeners = new Map();
  const videoId = 'video12345678';
  const liveUrls = new Set(options.liveUrls || [LIVE]);
  const networkErrorUrls = new Set(options.networkErrorUrls || []);
  const calls = { clients: [], captionFetches: [], proxyTranscript: 0 };

  class CustomEvent {
    constructor(type, init = {}) {
      this.type = type;
      this.detail = init.detail;
    }
  }

  const mapTracks = (list) => (list || []).map((t) => ({
    baseUrl: t.baseUrl,
    languageCode: t.language || 'en',
    name: { simpleText: t.name || 'English' },
    kind: t.isAutoGenerated ? 'asr' : undefined,
    vssId: t.vssId || 'a.en'
  }));

  const windowObj = {
    location: { href: `https://www.youtube.com/watch?v=${videoId}`, pathname: '/watch' },
    addEventListener(type, fn) {
      if (!listeners.has(type)) listeners.set(type, new Set());
      listeners.get(type).add(fn);
    },
    removeEventListener(type, fn) { listeners.get(type)?.delete(fn); },
    dispatchEvent(event) {
      if (event.type === 'ytai-request-player-prefs') {
        this.dispatchEvent(new CustomEvent('ytai-player-prefs-response', {
          detail: JSON.stringify({ videoId, activeCaptionTrack: null, captionRouting: null })
        }));
      }
      if (event.type === 'ytai-request-player-data') {
        this.dispatchEvent(new CustomEvent('ytai-player-data-response', {
          detail: JSON.stringify({ videoId, tracks: mapTracks(options.bridgeTracks) })
        }));
      }
      const handlers = listeners.get(event.type);
      if (!handlers) return true;
      for (const handler of [...handlers]) handler(event);
      return true;
    }
  };

  const context = {
    window: windowObj,
    globalThis: null,
    navigator: { language: 'en-US' },
    URL,
    CustomEvent,
    DOMParser: class { parseFromString() { return { querySelectorAll: () => [] }; } },
    document: {
      // No #movie_player: readiness gate times out fast and the retry loop runs.
      querySelector: () => null,
      querySelectorAll: () => []
    },
    StorageHelper: {
      outputLanguageToCaptionCode: () => null,
      getCachedTranscript: async () => null,
      cacheTranscript: async () => {}
    },
    chrome: {
      runtime: {
        sendMessage: async ({ action }) => {
          if (action === 'fetchCaptionTracks') {
            return { tracks: (options.proxyTracks || []).map((t) => ({ ...t, language: t.language || 'en' })) };
          }
          if (action === 'fetchTranscript') { calls.proxyTranscript += 1; return { entries: [] }; }
          return {};
        }
      }
    },
    fetch: async (url, opts) => {
      const raw = String(url);

      if (raw.startsWith('/youtubei/v1/player')) {
        const client = JSON.parse(opts.body).context.client.clientName;
        calls.clients.push(client);
        return {
          ok: true,
          json: async () => ({
            captions: {
              playerCaptionsTracklistRenderer: {
                captionTracks: mapTracks(options.clientTracks?.[client])
              }
            }
          })
        };
      }

      const base = raw.split('&fmt=')[0];
      calls.captionFetches.push(base);
      if (networkErrorUrls.has(base)) throw new TypeError('Failed to fetch');
      if (liveUrls.has(base)) {
        return { ok: true, text: async () => JSON.stringify({ events: [{ tStartMs: 0, segs: [{ utf8: 'live transcript' }] }] }) };
      }
      // Dead URL: HTTP 200, empty body — exactly what YouTube now returns.
      return { ok: true, status: 200, text: async () => '' };
    },
    setTimeout,
    clearTimeout,
    console
  };

  context.globalThis = context;
  context.__YTAI_TRANSCRIPT_RUNTIME_CONFIG = {
    maxAttempts: options.maxAttempts || 1,
    retryDelaysMs: [0, 0, 0],
    readinessTimeoutMs: 20,
    readinessPollMs: 5
  };

  vm.createContext(context);
  vm.runInContext(transcriptSource, context, { filename: 'transcript.js' });
  return { tx: context.globalThis.TranscriptExtractor, calls };
}

test('falls through to IOS when ANDROID tracks are all dead URLs', async () => {
  const h = createHarness({
    clientTracks: {
      ANDROID: [{ baseUrl: DEAD }],
      IOS: [{ baseUrl: LIVE }]
    }
  });

  const result = await h.tx.getTranscript();
  assert.equal(result.fullText, 'live transcript');
  assert.equal(result.source, 'innertube-ios');
  assert.deepEqual(h.calls.clients, ['ANDROID', 'IOS']);
});

test('falls through to the page bridge when every innertube client is dead', async () => {
  const h = createHarness({
    clientTracks: { ANDROID: [{ baseUrl: DEAD }], IOS: [{ baseUrl: DEAD }] },
    bridgeTracks: [{ baseUrl: LIVE }]
  });

  const result = await h.tx.getTranscript();
  assert.equal(result.source, 'page-bridge');
  assert.equal(result.fullText, 'live transcript');
});

test('falls through to the service-worker proxy as the last source', async () => {
  const h = createHarness({
    clientTracks: { ANDROID: [{ baseUrl: DEAD }], IOS: [{ baseUrl: DEAD }] },
    proxyTracks: [{ baseUrl: LIVE }]
  });

  const result = await h.tx.getTranscript();
  assert.equal(result.source, 'sw-proxy');
});

test('a dead URL shared by two sources is fetched only once', async () => {
  const h = createHarness({
    clientTracks: { ANDROID: [{ baseUrl: DEAD }], IOS: [{ baseUrl: DEAD }] },
    bridgeTracks: [{ baseUrl: DEAD }],
    liveUrls: []
  });

  await assert.rejects(() => h.tx.getTranscript(), /TRANSCRIPT_EMPTY_FINAL/);
  assert.deepEqual(h.calls.captionFetches, [DEAD], 'identical URL must not be refetched');
});

test('reports EMPTY_FINAL (not UNAVAILABLE) when tracks exist but never resolve', async () => {
  const h = createHarness({
    clientTracks: { ANDROID: [{ baseUrl: DEAD }] },
    liveUrls: []
  });

  await assert.rejects(() => h.tx.getTranscript(), /TRANSCRIPT_EMPTY_FINAL/);
});

test('a URL proven dead is never sent to the service-worker proxy', async () => {
  // A 200/empty response means YouTube rejected the URL itself — verified
  // against live YouTube to be identical for json3, srv3, vtt and ttml, with
  // and without credentials. The proxy would fetch the same nothing.
  const h = createHarness({
    clientTracks: { ANDROID: [{ baseUrl: DEAD }], IOS: [{ baseUrl: LIVE }] }
  });

  const result = await h.tx.getTranscript();
  assert.equal(result.source, 'innertube-ios');
  assert.equal(h.calls.proxyTranscript, 0, 'dead URL must not trigger a proxy fetch');
});

test('a dead URL is not retried by a later source or a later attempt', async () => {
  const h = createHarness({
    clientTracks: { ANDROID: [{ baseUrl: DEAD }], IOS: [{ baseUrl: DEAD }] },
    bridgeTracks: [{ baseUrl: DEAD }],
    proxyTracks: [{ baseUrl: DEAD }],
    liveUrls: [],
    maxAttempts: 3
  });

  await assert.rejects(() => h.tx.getTranscript(), /TRANSCRIPT_EMPTY_FINAL/);
  assert.deepEqual(
    h.calls.captionFetches,
    [DEAD],
    'one fetch total across every source and attempt'
  );
  assert.equal(h.calls.proxyTranscript, 0);
});

test('a non-dead direct failure still falls back to the proxy', async () => {
  // Distinguishes "URL is dead" from "this context could not fetch it" — the
  // latter is exactly what the service-worker proxy exists to rescue.
  const h = createHarness({
    clientTracks: { ANDROID: [{ baseUrl: 'https://x/timedtext?lang=en&neterr=1' }] },
    networkErrorUrls: ['https://x/timedtext?lang=en&neterr=1'],
    liveUrls: []
  });

  await assert.rejects(() => h.tx.getTranscript(), /TRANSCRIPT_EMPTY_FINAL/);
  assert.equal(h.calls.proxyTranscript, 1, 'a transport failure must still try the proxy');
});

test('reports UNAVAILABLE when no source produces any track at all', async () => {
  const h = createHarness({ clientTracks: {}, liveUrls: [] });

  await assert.rejects(() => h.tx.getTranscript(), /TRANSCRIPT_UNAVAILABLE/);
});
